# Generated by Django 2.2.18 on 2021-08-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='project',
        ),
    ]
