# Generated by Django 2.2.18 on 2021-08-04 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_finding_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
    ]
