# Generated by Django 2.2.18 on 2021-08-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_finding_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='code',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='finding',
            name='size',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='web',
            name='fuzzer_status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
