# Generated by Django 2.2.18 on 2021-08-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210804_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
