# Generated by Django 2.2.18 on 2021-08-05 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_finding_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
    ]
