# Generated by Django 2.2.18 on 2021-08-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210805_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='project',
        ),
    ]
